package com.msanc.elektrikatolyesi;

/** A navigable map of the discipline. Each article names the assumptions of its formula. */
public final class Atlas {
    private Atlas() {}
    public static final class Topic {
        public final String icon,title,level,summary,concept,formula,scenario;
        public final int route,tool;
        Topic(String icon,String title,String level,String summary,String concept,String formula,String scenario,int route,int tool){this.icon=icon;this.title=title;this.level=level;this.summary=summary;this.concept=concept;this.formula=formula;this.scenario=scenario;this.route=route;this.tool=tool;}
    }
    public static final Topic[] ALL={
        new Topic("⚡","Devre temelleri","BAŞLANGIÇ","Akım, gerilim, direnç ve enerji","Akım kapalı bir yol gerektirir. Gerilim potansiyel farkıdır; direnç akımı sınırlar. Seri elemanlarda akım, paralel kollarda gerilim ortaktır. Kirchhoff düğüm ve çevre yasaları daha karmaşık devrelerin temelidir.","I=U/R  •  P=UI  •  ΣIgiren=ΣIçıkan","9 V pil, anahtar ve ampulü atölyede birleştir. Anahtarı açınca yolun neden kesildiğini izle.",0,0),
        new Topic("∿","AC ve fazörler","TEMEL","Frekans, RMS ve empedans","Sinüzoidal bir büyüklüğün etkin değeri eşdeğer ısıl etkiyi verir. Dirençte gerilim ve akım aynı fazdadır; bobin ve kondansatör faz kaydırır. Fazör hesabı tek frekanslı kararlı durum için kullanılır.","T=1/f  •  Z=R+jX  •  |Z|=√(R²+X²)","Aynı RMS gerilimde dirençli ve endüktif yükün akım fazını karşılaştır.",1,0),
        new Topic("△","Üç faz ve güç","ORTA","Dengeli sistem, P, Q ve S","Üç fazlı dengeli yükte fazlar 120° ayrılır. Hat gerilimi ve akımıyla görünür güç hesaplanır. cosφ yalnız temel sinüzoidal bileşenin faz kaymasını anlatır; harmonikli sistemde toplam güç faktörü ayrı incelenir.","S=√3 UI  •  P=√3 UIcosφ  •  Q=Ptanφ","400 V, 10 A, cosφ=0,8 için yaklaşık aktif gücü hesapla.",1,0),
        new Topic("▰","Kablo ve gerilim düşümü","MÜHENDİSLİK","Kesit yalnız amper tablosu değildir","Akım taşıma kapasitesi döşeme şekli, damar sayısı, yalıtım, sıcaklık, gruplanma ve harmoniklere bağlıdır. Gerilim düşümü ve kısa devre termik dayanımı ayrıca kontrol edilir. Hesap aracının tablo kapsamını değiştirmeden başka sahaya uygulama.","IB≤Iz·kT·kG  •  ΔU3φ=√3 I(Rcosφ+Xsinφ)L","40°C'de yan yana iki devre için 6 mm² Cu/PVC yöntemi C kapasitesini incele.",2,2),
        new Topic("◉","Kompanzasyon","MÜHENDİSLİK","Reaktif güç ve kademe kontrolü","Kondansatör bankı endüktif reaktif gücü dengeler. İhtiyaç aktif güç ve iki güç katsayısı açısından hesaplanır. Değişken yükte kademe düzeni, akım trafosu yönü, boşta çalışma, aşırı kompanzasyon ve harmonik rezonans incelenir.","Qc=P(tanφ1−tanφ2)","100 kW, cosφ 0,75 → 0,93 için kvar bul; ardından kademeleri düşün.",3,1),
        new Topic("⚙","Motor kumandası","UYGULAMA","Kontaktör, STOP, START ve yardımcı kontak","STOP kontağı normalde kapalı, START normalde açıktır. Bobin çekince yardımcı kontak START'a paralel tutma yolu oluşturur. Termik röle ve acil stop koruma tasarımında ayrıca yer alır. Atölyedeki 24 V devre yalnız bir mantık simülasyonudur.","L → STOP(NC) → [START(NO) ∥ KM(NO)] → A1 → A2 → N","Panoyu bağla, START'ı bırakınca motorun çalışmasını sağla, STOP ile durdur.",4,-1),
        new Topic("▣","Transformatörler","MÜHENDİSLİK","Sarım oranı, uk% ve arıza","Nominal akım görünür güç ve hat geriliminden çıkar. uk% trafo empedansını temsil eder. Ik≈In/uk(pu) yalnız trafo uçları için kaba yaklaşım sunar; üst şebeke, kablo, DC bileşen ve sıcaklık dahil edilmelidir.","In=S/(√3U)  •  Ik≈In·100/uk%","1000 kVA, 400 V, uk=6% için nominal ve yaklaşık kısa devre akımını karşılaştır.",4,5),
        new Topic("⏚","Koruma ve topraklama","MÜHENDİSLİK","TT, TN, IT; hata yolu ve açma","Elektrik çarpmasına karşı koruma yalnız bir topraklama direnç değeriyle belirlenmez. Sistem düzeni, hata döngüsü, koruma cihazı ve açma süresi birlikte değerlendirilir. Seçicilik için üretici zaman-akım eğrileri ve kısa devre kesme kapasitesi gerekir.","IB≤In≤Iz  •  Zs·Ia≤U0 (TN yaklaşımı)","Bir arıza için hangi cihazın açacağını ve üst şalterin neden kapalı kalması gerektiğini düşün.",5,4),
        new Topic("≋","Güç elektroniği","İLERİ","Doğrultucu, DC/DC ve inverter","Diyot doğrultucular AC'yi DC'ye çevirir. Anahtarlamalı dönüştürücüler görev döngüsü ve enerji depolama elemanlarıyla gerilimi değiştirir. İnverterler DC baradan kontrollü AC oluşturur. Kayıp, EMI ve koruma ideal denklemlerden sapar.","İdeal buck: Vout≈D·Vin  (sürekli iletim)","48 V DC kaynaktan ideal buck ile 12 V için yaklaşık görev döngüsü D=0,25.",-1,-1),
        new Topic("◇","Analog elektronik","ORTA","Diyot, transistor ve op-amp","Diyot tek yönde iletim davranışı gösterir. Transistor anahtar veya yükselteç olarak kullanılır. Negatif geri beslemeli ideal op-amp denklemleri doyuma ve besleme sınırlarına dikkat ederek uygulanır.","Tersleyen op-amp: Av≈−Rf/Rin","Rf=20 kΩ ve Rin=10 kΩ için ideal kazanç −2; çıkışın besleme sınırını kontrol et.",-1,-1),
        new Topic("01","Dijital mantık","ORTA","Kapılar, flip-flop ve durum","VE, VEYA ve DEĞİL kapıları doğruluk tablosuyla tanımlanır. Kombinasyonel devre yalnız girişe, ardışıl devre önceki duruma da bağlıdır. Kontak mantığı ile dijital mantık arasında benzerlikler vardır.","Y=A·B  •  Y=A+B  •  Y=¬A","Motor izin şartını iki ayrı emniyet kontağı VE bağlantısı olarak modelle.",-1,-1),
        new Topic("☷","Otomasyon ve PLC","İLERİ","Giriş, çıkış, tarama döngüsü","PLC girişleri okur, mantığı işletir ve çıkışları günceller. Kontaktör tutma mantığı ladder üzerinde kurulabilir. Güvenlik fonksiyonları sıradan PLC mantığına bırakılmaz; uygun güvenlik mimarisi gerekir.","Çıkış = izin ∧ (başlat ∨ tutma)","START ve tutma kontağının OR, STOP'un AND rolünü panel simülasyonunda gözle.",-1,-1),
        new Topic("⌁","Ölçme ve güç kalitesi","UYGULAMA","Multimetre, ölçüm güvenliği ve harmonikler","Gerilim paralel, akım uygun ölçü düzeneğiyle seri ya da pensle ölçülür. Ölçüm kategorisi ve cihaz sınırı sahaya uygun olmalıdır. THD, dengesizlik ve üçüncü harmonik nötr akımını etkileyebilir.","THD_I=√(Σ I_h²)/I_1  (h≥2)","Bir kompanzasyon tasarımında ölçülen harmonik düzeyi olmadan reaktör seçimini kesinleştirme.",5,-1),
        new Topic("☀","Yenilenebilir enerji","İLERİ","PV, inverter, depolama","PV dizisinde sıcaklık gerilimleri, ışınım akımı etkiler. MPPT çalışma noktasını izler; inverter ve batarya yönetimi sisteme sınırlar getirir. Kablo, koruma ve bağlantı şartları ayrı projelendirilir.","P≈Vmp·Imp  (anlık MPP)","Dizi açık devre geriliminin soğukta artabileceğini hesaba kat.",-1,-1),
        new Topic("▤","Şebeke ve proje","MÜHENDİSLİK","Üretimden yüke sistem yaklaşımı","Yük tahmini, kısa devre, gerilim seviyesi, kayıp, koruma koordinasyonu ve seçicilik birbiriyle bağlantılıdır. Tek bir hesap ekranının sonucu sistemin tamamını doğrulamaz. Etüt, tek hat şeması ve ölçüm verileri birlikte ele alınır.","P_kayıp≈I²R  •  yük akışı: P,Q,U,θ","Bir hat kesiti artınca hem kayıp hem gerilim düşümünün nasıl değiştiğini araştır.",5,3)
    };
}
